### ISSUE TITLE
Quiz entity 추가, 관련 로직 수정

### ISSUE THREAD

**Issue by paran22** [paran22/RoomEscape_BE#48]
**Description**
데이터 관리 전략 설정에 따라 게임 종료 시 Quiz를 삭제하지 않고, state만 변경

**Todo**
- [x] Quiz entity에 pass, state 추가
- [x] Quiz 조회하기 api에서 Quiz 생성 시 entity 변경 부분 반영
- [x] Quiz 완료 api시 pass를 success로 변경해주는 것으로 수정
- [x] #53

**ETC**
Quiz 완료 api 변경 부분 프론트엔드에 공유하기

**Comment by paran22** [comment]
Todo
- [ ] Quiz 조회하기 api response에 pass 추가

**Comment by paran22** [comment]
Todo
- [ ] 게임 종료 api에서 퀴즈 삭제하지 않는 것으로 수정
