### ISSUE TITLE
Rest Api Url 규칙에 따른 전체적인 수정

### ISSUE THREAD

**Issue by wonjaeban** [paran22/RoomEscape_BE#50]
**Description**
Rest Api Url을 적합한 규칙에 따라 작성하기 위해서 전체적인 수정이 필요하다.

**Todo**
- [x] 방 개설하기 Url 복수형으로 수정
- [x] 방 조회하기 Url 복수형으로 수정
- [x] 방 참여하기 Url 복수형으로 수정
- [x] 게임 종료후 랭킹 조회하기 Url 복수형으로 수정
- [x] 코멘트 입력하기 Url 복수형으로 수정
- [x] 게임 리소스 저장하기 Url 복수형으로 수정
- [x] 게임 시작하기 Url 복수형으로 수정
- [x] 게임 종료하기 Url 전체적인 수정
- [x] clue 생성하기 Url  전체적인 수정
- [x] clue 조회하기 Url 전체적인 수정
- [x] quiz 조회하기 Url 전체적인 수정
- [x] quiz 완료하기 Url 전체적인 수정

**ETC**
전체적인 수정은 복수형으로 수정 뿐만 아니라 순서 등도 바뀜을 의미합니다.
