### ISSUE TITLE
Room entity에 column 추가, 관련 로직 수정

### ISSUE THREAD

**Issue by paran22** [paran22/RoomEscape_BE#58]
**Description**
데이터 관리 전략 설정에 따라 게임 종료 시 Room을 삭제하지 않고, state만 변경

**Todo**
- [x] #62
- [x] #63
- [x] 게임 종료하기 api에서 Room의 state를 CLOSE로 변경, pass를 SUCCESS로 변경
- [x] #61

**ETC**
게임 실패시 처리 로직은 프론트엔드와 논의 후 별도 이슈로 관리 예정

**Comment by paran22** [comment]
**Todo**
- [ ] Room entity에 userNum 추가(기본값 null)
- [ ] 게임 종료 api에 userNum 입력

**변경 사유**
게임 종료 시 User가 삭제되기 때문에 Room의 인원 수 알 수 없음
추후 S3로 데이터 이전할 때 분석용으로 사용하기 위함
