### ISSUE TITLE
Clue와 Room 연관관계 끊기

### ISSUE THREAD

**Issue by paran22** [paran22/RoomEscape_BE#60]
**Description**
Clue는 게임 종료 후 삭제 처리를 위해 Room과 연관관계를 끊고, roomId만 저장해서 조회만 가능하게 수정

**Todo**
- [x] Clue entity 수정 : Room 삭제하고 roomId 추가
- [x] Clue 생성하기 수정
- [x] Clue 조회하기 오류 없는지 확인

**ETC**
게임 종료 api에서 Clue만 삭제하는지 확인
